### PR TITLE
Style updates; latest stories slider; new mobile menu breakpoint

### PR DESCRIPTION
**Pull request by kidcompassion**
This PR includes:
- Requested style updates
- Changes to nav
- JS to make the latest stories slider work
- New breakpoint for the hamburger menu

You'll likely need to do a bower install, since this branch now includes less.js for custom bootstrap compiling. 

I have three things outstanding: porting the top latest stories slider JS to the footer; correcting the most frustrating layout bug EVER on the search toggle in xs viewports; and adding some nicer styles to the latest stories slider since adding real content kind of killed the css. 

I'll be working throughout the weekend, and will let you now when the above 3 are resolved. Let me know if you need anything!

### CODE REVIEW

**Comment by kidcompassion** [comment]
Hey @alexgreen, my updates are all in this branch now. Going forward I'm going to do what I should've been doing in the first place, which is create a new branch for each feature or major change, instead of dumping everything into one PR.

**Comment by kidcompassion** [comment]
Also @alexgreen, one more thing - I'm debugging some issues I've found in the latest stories slider, so do you mind pushing up your latest changes - whatever stage they may be in - whenever you have a sec? I want to make sure it's going to work with any new code. Thanks! :smiley_cat:

**Comment by alexgreen** [comment]
Thanks for the recent updates @kidcompassion !
I’ll merge them into my local and then push everything once I’m through a few more commits.

FYI, the way I usually handle your PRs  is like this:
git fetch origin sp-based-off-ag-atomic:sp-based-off-ag-atomic
(Basically I’m assuming that sp-based-off-ag-atomic is your personal master branch. If not, could you specify one?)
Then I merge sp-based-off-ag-atomic into one of my local branches. After that, if everything is successful I will either merge your PR on github or just push my local master to github.

Do you usually merge all your new commits into sp-based-off-ag-atomic? If not, then I likely won’t see them and they may not get merged into the master. Does this work for you? I’m open to some other kind of workflow, but often I don’t want to merge a PR directly into the master because I’ve found it can be annoying to reverse. It seems pretty odd that Github doesn’t let me change the target branch of a PR, but maybe I’m missing something.

**Comment by alexgreen** [comment]
(In this case I can see that your PR specifies addition/recompile-bootstrap so that's the one I'll fetch to merge locally.)

**Comment by alexgreen** [comment]
@kidcompassion I can't merge your branch due to the following error:

> alexg@ag:~/WEB-DEVELOPMENT/design-article.thetyee.ca$ git fetch origin addition/recompile-bootstrap:ag-Sally_test_merge-23mar
> fatal: Refusing to fetch into current branch refs/heads/ag-Sally_test_merge-23mar of non-bare repository

I haven't run into the problem before and I've never seen a non-bare repository. Any idea what's going on?

**Comment by alexgreen** [comment]
Sorry, disregard my comment about the merge error! I think it was just because I had the local branch checked out.

**Comment by alexgreen** [comment]
This is getting really close! Just a few things I noticed:

**Nav**
- Nav collapses to hamburger much too soon. —> because of gap around logo
- Spacing between all buttons should be equal. 

**Latest stories**
- Slider only navigates rightwards. Can we add a left arrow?
- When navigating (rightwards) there’s a really long lag before the new images get loaded. Can they load quicker? If not then we should put in grey boxes with a loading symbol gif as placeholders.
- Remove top rule
- Remove bottom rule
- Make vertical dividers grey

**Expanded (stacked) hamburger nav**
- At some widths the Latest Stories appears horizontally within a hamburger, which is odd. Also, it has no nav arrow in this state. 
- The stacked nav must allow multiple items to be expanded simultaneously. I.e. if I click to expand the Latest Stories and scroll down past them where I then decide to expand More, Latest Stories should remain expanded. Otherwise the whole menu shifts upwards and I have to scroll up to see the top of the More list. —So, currently the menu expansion behaviour actually conceals the very thing I’m trying to see. (Hard to explain this clearly in words, but try it in a view 700px wide and you’ll see what I mean.)

**Article body**
Please keep the slideshow commented out until we have a chance to style it properly.

1-nav-spacing
2-hamburger-collapse
3-latest-stories
4-breakpoint-conflict

**Comment by kidcompassion** [comment]
@alexgreen was there a tablet/phablet design done? I feel like I saw one at one point but I'll be damned if I can find it in basecamp.

**Comment by alexgreen** [comment]
There were only 2 widths mocked up. The narrow one is actually quite wide, phablet territory but not really as wide as a tablet.

**Comment by alexgreen** [comment]
@kidcompassion Do my comments make sense? Here's a comparison of the previous nav iteration and the new one at the same width, showing how the new one collapses prematurely.

nav-oldversion
nav-newversion

**Comment by alexgreen** [comment]
I'm also noticing that the search button stacks on android mobile chrome at 768px viewport width. I guess that's a 2x width dimension so it probably translates into width of 384 on laptop/desktop. (You can actually observe the same behaviour on laptop when width < 397px.)

mobile-768px

**Comment by kidcompassion** [comment]
Will do as soon as all functionality is completed.

**Pull request closed without merging**
