### PR TITLE
Navigation Design Update

### PR DESCRIPTION
**Pull request by kidcompassion**
This PR:

-Adds in style changes to match @alexgreen's sweet new design. Also resolves the flagged z-index issue where the dropdown is hidden by certain page elements.

-Missing some of the custom icons, and right nav could be spaced better, but I'm stopping for the night because I'm going to give myself nosebleed trying to make it perfect :grin: Once the design is locked in I'll be tireless in my pursuit!

-FYI, this has only been tested in Chrome, using the device emulator. No real devices.

Screencaps of nav (though in hindsight doing the whole mobile page screencap may have been overkill):

the tyee article page mobile expanded
the tyee article page mobile
the tyee article page

### CODE REVIEW

**Comment by kidcompassion** [comment]
Next time I'm going to make it even longer so you have to scroll even more, @alexgreen :smiley_cat:

**Comment by alexgreen** [comment]
Great, I’ll do a test merge!

Based on the screen caps, it looks like Disqus is still overflowing into the footer. Best to just leave the comments section out of any PR until it’s no longer breaking the layout. 

As I mentioned there was a similar problem with the dropdown nav overflowing into the article body, and that issue was only showing up when the latest-stories was expanded (which isn’t the case in your screen caps) so I suspect that may also still be a problem. ?

**Comment by alexgreen** [comment]
Thanks, I need the exercise! ( ͝° ͜ʖ͡°)

**Comment by alexgreen** [comment]
> -FYI, this has only been tested in Chrome, using the device emulator. No real devices.
> 
> Yup, that’s what I’m doing. This is still the prototype phase so no need to get bogged down in cross-browser issues yet. We’re not going into uncharted territory so it should be possible to get all this to work across browsers without too much trouble.
>

**Comment by kidcompassion** [comment]
Oh sorry, I think I misunderstood; are you wanting the expanded nav to push
the article body down the page as opposed to expand overtop of it? If so I
can for sure switch it tomorrow; I thought your concern was just the
z-index stuff.

**Comment by alexgreen** [comment]
> Oh sorry, I think I misunderstood; are you wanting the expanded nav to push
> the article body down the page as opposed to expand overtop of it? If so I
> can for sure switch it tomorrow; I thought your concern was just the
> z-index stuff.
> If you look at the screen caps I posted (yesterday?) you’ll see that nav did neither. It was colliding with the article body and running behind various elements. Please just look at the screen caps. 
> And this is also what Disqus does in your own screen cap (and what I suspect the nav is still doing when latest-stories are expanded).
> So what’s happening is obviously not what we would want.

…that being said. The article page mockups from draft 3 and draft 5 show the article body (and every other element below the nav bar) being pushed downwards when the nav drop-downs expand. So yes, that’s the design intention.

**Comment by kidcompassion** [comment]
Yup, I have looked at the screen caps. When I say "z-index issue", I'm
referring to the same thing as you - how because of its z-index, the nav
was hiding behind the other elements. This is resolved in the PR.

Re: menu pushing content down, sure I'll change it when i have a sec
tomorrow; there are a few things I need to add anyway! Also, f you have an
updated version of the design with an expanded nav, can you attach it here
or in Basecamp? The last example I have of a narrow viewport with an
expanded nav is in a zip file in Basecamp, from draft 2 (unless I've missed
an expanded nav version of # 5 somewhere?).

**Comment by alexgreen** [comment]
> Yup, I have looked at the screen caps. When I say "z-index issue", I'm
> referring to the same thing as you - how because of its z-index, the nav
> was hiding behind the other elements. This is resolved in the PR.

Ok, good. because the comment block in the PR is still displaying the same collision and z-index issue. Is that something you’re looking into?

>  Also, f you have an
> updated version of the design with an expanded nav, can you attach it here
> or in Basecamp?

Draft 5 mockups have been in basecamp: 
https://basecamp.com/1929296/projects/9481270/messages/53811335 https://basecamp.com/1929296/projects/9481270/messages/53811335
Narrow viewport of expanded nav isn’t included because the only change is the colours.

**Comment by alexgreen** [comment]
Nav bar is looking much better! (I have a chance to merge it now.)
But there’s still a few things to fix:

• Nav bar needs more tuning for horizontal spacing of nav links, vertical alignment of the nav links, and length of bottom borders (should come much closer to logo in wider viewports). Bottom borders also shouldn’t disappear in narrow views.

• The nav bar is breaking the layout at viewports of 768px and higher. It forces the page to get about 10px wider than 100% and causes sideways scrolling. This has been happening for weeks, but I didn’t notice it until today. Something seems to be forcing 
<div class="[ row navbar-collapse ] menu collapse" id="bs-example-navbar-collapse-1" style="height: 0px;">
to expand. Not sure what the cause is. It’s distracting and makes it hard to test the responsive layout, so I’m going to comment out the nav bar until this is resolved.

• And there’s the issue of the Disqus comments breaking the layout as I mentioned.

**Comment by alexgreen** [comment]
I've prevented the nav-bar from breaking the layout width by commenting out your css menu width rule:
.menu {
  /\* width: 100vw;  --AG--*/
  padding: 0px;
  margin: 0px;
  border-top: none;
}
...not sure whether this messes up anything you've done, but at least it means we can show the navbar.

**Comment by alexgreen** [comment]
So, with that change I've now merged the commits from your branch into the master and into the github pages.

**Comment by kidcompassion** [comment]
@alexgreen i totally forgot to tag you in this last week when i fixed the mobile nav. I also commented out the disqus code, since their test code appends a bunch of extra junk that breaks the layout.

**Comment by kidcompassion** [comment]
Killing this PR since I've added the majority of the updates in my new branch, which includes the JS.

**Pull request closed without merging**
